name: Publish to GAE

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:

 publish:
  runs-on: ubuntu-latest
  steps: 
  - name: Checkout
    uses: actions/checkout@v2.3.3 
  - name: Latest Gcloud
    uses: setup-gcloud@latest  
  - name: Initialize Google Cloud SDK
    uses: zxyle/publish-gae-action@master
    with:
     service_account_email: ${{ secrets.GCP_SA_EMAIL }}
     service_account_key: ${{ secrets.GCP_SA_KEY }}
     project_id: ${{ secrets.PROJECT_ID }}
     # An optional variables parameter can be used
     gae_variables: ${{ secrets.GAE_VARIABLES }}
    
  - name: Publish app to Google App Engine
    run: |
      # This client-secret.json is converted by GCP_SA_KEY.
      gcloud auth activate-service-account ${{ secrets.GCP_SA_EMAIL }} --key-file=client-secret.json
      gcloud config set project ${{ secrets.PROJECT_ID }}
      gcloud -q app deploy app.yaml --promote
